// All supported languages with their labels and categories
export const languages = {
  fr: {
    label: 'Français',
    flag: '🇫🇷',
    categories: {
      finances: 'Finances',
      emploi: 'Emploi',
      sante: 'Santé',
      logement: 'Logement',
      droit: 'Droit',
      relations: 'Relations',
      luxe: 'Luxe',
      retraite: 'Retraite',
    },
    articlesLabel: 'Articles en Français',
    allArticles: 'Tous les articles',
    readMore: 'Lire la suite',
    backToArticles: '← Retour aux articles',
    publishedOn: 'Publié le',
    categoryLabel: 'Catégorie',
    noArticles: 'Aucun article dans cette catégorie pour le moment.',
  },
  en: {
    label: 'English',
    flag: '🇬🇧',
    categories: {
      finances: 'Finances',
      employment: 'Employment',
      health: 'Health',
      housing: 'Housing',
      law: 'Law',
      relationships: 'Relationships',
      luxury: 'Luxury',
      retirement: 'Retirement',
    },
    articlesLabel: 'English Articles',
    allArticles: 'All articles',
    readMore: 'Read more',
    backToArticles: '← Back to articles',
    publishedOn: 'Published on',
    categoryLabel: 'Category',
    noArticles: 'No articles in this category yet.',
  },
  de: {
    label: 'Deutsch',
    flag: '🇩🇪',
    categories: {
      finanzen: 'Finanzen',
      arbeit: 'Arbeit',
      gesundheit: 'Gesundheit',
      wohnen: 'Wohnen',
      recht: 'Recht',
      beziehungen: 'Beziehungen',
      luxus: 'Luxus',
      rente: 'Rente',
    },
    articlesLabel: 'Deutsche Artikel',
    allArticles: 'Alle Artikel',
    readMore: 'Weiterlesen',
    backToArticles: '← Zurück zu den Artikeln',
    publishedOn: 'Veröffentlicht am',
    categoryLabel: 'Kategorie',
    noArticles: 'Noch keine Artikel in dieser Kategorie.',
  },
  es: {
    label: 'Español',
    flag: '🇪🇸',
    categories: {
      finanzas: 'Finanzas',
      empleo: 'Empleo',
      salud: 'Salud',
      vivienda: 'Vivienda',
      derecho: 'Derecho',
      relaciones: 'Relaciones',
      lujo: 'Lujo',
      jubilacion: 'Jubilación',
    },
    articlesLabel: 'Artículos en Español',
    allArticles: 'Todos los artículos',
    readMore: 'Leer más',
    backToArticles: '← Volver a los artículos',
    publishedOn: 'Publicado el',
    categoryLabel: 'Categoría',
    noArticles: 'No hay artículos en esta categoría todavía.',
  },
  it: {
    label: 'Italiano',
    flag: '🇮🇹',
    categories: {
      finanze: 'Finanze',
      lavoro: 'Lavoro',
      salute: 'Salute',
      alloggio: 'Alloggio',
      diritto: 'Diritto',
      relazioni: 'Relazioni',
      lusso: 'Lusso',
      pensione: 'Pensione',
    },
    articlesLabel: 'Articoli in Italiano',
    allArticles: 'Tutti gli articoli',
    readMore: 'Leggi di più',
    backToArticles: '← Torna agli articoli',
    publishedOn: 'Pubblicato il',
    categoryLabel: 'Categoria',
    noArticles: 'Nessun articolo in questa categoria per il momento.',
  },
  da: {
    label: 'Dansk',
    flag: '🇩🇰',
    categories: {
      finans: 'Finans',
      arbejde: 'Arbejde',
      sundhed: 'Sundhed',
      bolig: 'Bolig',
      jura: 'Jura',
      relationer: 'Relationer',
    },
    articlesLabel: 'Artikler på dansk',
    allArticles: 'Alle artikler',
    readMore: 'Læs mere',
    backToArticles: '← Tilbage til artikler',
    publishedOn: 'Udgivet den',
    categoryLabel: 'Kategori',
    noArticles: 'Ingen artikler i denne kategori endnu.',
  },
  nl: {
    label: 'Nederlands',
    flag: '🇳🇱',
    categories: {
      financien: 'Financiën',
      werk: 'Werk',
      gezondheid: 'Gezondheid',
      huisvesting: 'Huisvesting',
      recht: 'Recht',
      relaties: 'Relaties',
    },
    articlesLabel: 'Artikelen in het Nederlands',
    allArticles: 'Alle artikelen',
    readMore: 'Lees meer',
    backToArticles: '← Terug naar artikelen',
    publishedOn: 'Gepubliceerd op',
    categoryLabel: 'Categorie',
    noArticles: 'Nog geen artikelen in deze categorie.',
  },
  sv: {
    label: 'Svenska',
    flag: '🇸🇪',
    categories: {
      ekonomi: 'Ekonomi',
      arbete: 'Arbete',
      halsa: 'Hälsa',
      bostad: 'Bostad',
      ratt: 'Rätt',
      relationer: 'Relationer',
    },
    articlesLabel: 'Artiklar på svenska',
    allArticles: 'Alla artiklar',
    readMore: 'Läs mer',
    backToArticles: '← Tillbaka till artiklar',
    publishedOn: 'Publicerad den',
    categoryLabel: 'Kategori',
    noArticles: 'Inga artiklar i denna kategori ännu.',
  },
  pl: {
    label: 'Polski',
    flag: '🇵🇱',
    categories: {
      finanse: 'Finanse',
      praca: 'Praca',
      zdrowie: 'Zdrowie',
      mieszkanie: 'Mieszkanie',
      prawo: 'Prawo',
      relacje: 'Relacje',
    },
    articlesLabel: 'Artykuły po polsku',
    allArticles: 'Wszystkie artykuły',
    readMore: 'Czytaj więcej',
    backToArticles: '← Powrót do artykułów',
    publishedOn: 'Opublikowano',
    categoryLabel: 'Kategoria',
    noArticles: 'Brak artykułów w tej kategorii.',
  },
  pt: {
    label: 'Português',
    flag: '🇧🇷',
    categories: {
      financas: 'Finanças',
      emprego: 'Emprego',
      saude: 'Saúde',
      moradia: 'Moradia',
      direito: 'Direito',
      relacionamentos: 'Relacionamentos',
    },
    articlesLabel: 'Artigos em Português',
    allArticles: 'Todos os artigos',
    readMore: 'Leia mais',
    backToArticles: '← Voltar aos artigos',
    publishedOn: 'Publicado em',
    categoryLabel: 'Categoria',
    noArticles: 'Nenhum artigo nesta categoria ainda.',
  },
  fi: {
    label: 'Suomi',
    flag: '🇫🇮',
    categories: {
      talous: 'Talous',
      tyo: 'Työ',
      terveys: 'Terveys',
      asuminen: 'Asuminen',
      oikeus: 'Oikeus',
      suhteet: 'Suhteet',
    },
    articlesLabel: 'Artikkelit suomeksi',
    allArticles: 'Kaikki artikkelit',
    readMore: 'Lue lisää',
    backToArticles: '← Takaisin artikkeleihin',
    publishedOn: 'Julkaistu',
    categoryLabel: 'Kategoria',
    noArticles: 'Ei artikkeleita tässä kategoriassa vielä.',
  },
  id: {
    label: 'Indonesia',
    flag: '🇮🇩',
    categories: {
      keuangan: 'Keuangan',
      pekerjaan: 'Pekerjaan',
      kesehatan: 'Kesehatan',
      perumahan: 'Perumahan',
      hukum: 'Hukum',
      hubungan: 'Hubungan',
    },
    articlesLabel: 'Artikel bahasa Indonesia',
    allArticles: 'Semua artikel',
    readMore: 'Baca selengkapnya',
    backToArticles: '← Kembali ke artikel',
    publishedOn: 'Diterbitkan pada',
    categoryLabel: 'Kategori',
    noArticles: 'Belum ada artikel dalam kategori ini.',
  },
  ms: {
    label: 'Melayu',
    flag: '🇲🇾',
    categories: {
      kewangan: 'Kewangan',
      pekerjaan: 'Pekerjaan',
      kesihatan: 'Kesihatan',
      perumahan: 'Perumahan',
      undangundang: 'Undang-undang',
      perhubungan: 'Perhubungan',
    },
    articlesLabel: 'Artikel Melayu',
    allArticles: 'Semua artikel',
    readMore: 'Baca lagi',
    backToArticles: '← Kembali ke artikel',
    publishedOn: 'Diterbitkan pada',
    categoryLabel: 'Kategori',
    noArticles: 'Tiada artikel dalam kategori ini lagi.',
  },
  ro: {
    label: 'Română',
    flag: '🇷🇴',
    categories: {
      finante: 'Finanțe',
      munca: 'Muncă',
      sanatate: 'Sănătate',
      locuinta: 'Locuință',
      drept: 'Drept',
      relatii: 'Relații',
    },
    articlesLabel: 'Articole în română',
    allArticles: 'Toate articolele',
    readMore: 'Citește mai mult',
    backToArticles: '← Înapoi la articole',
    publishedOn: 'Publicat pe',
    categoryLabel: 'Categorie',
    noArticles: 'Niciun articol în această categorie încă.',
  },
  el: {
    label: 'Ελληνικά',
    flag: '🇬🇷',
    categories: {
      oikonomika: 'Οικονομικά',
      ergasia: 'Εργασία',
      ygeia: 'Υγεία',
      stegasi: 'Στέγαση',
      dikaio: 'Δίκαιο',
      sxeseis: 'Σχέσεις',
    },
    articlesLabel: 'Άρθρα στα Ελληνικά',
    allArticles: 'Όλα τα άρθρα',
    readMore: 'Διαβάστε περισσότερα',
    backToArticles: '← Πίσω στα άρθρα',
    publishedOn: 'Δημοσιεύτηκε στις',
    categoryLabel: 'Κατηγορία',
    noArticles: 'Δεν υπάρχουν ακόμα άρθρα σε αυτή την κατηγορία.',
  },
  cs: {
    label: 'Čeština',
    flag: '🇨🇿',
    categories: {
      finance: 'Finance',
      prace: 'Práce',
      zdravi: 'Zdraví',
      bydleni: 'Bydlení',
      pravo: 'Právo',
      vztahy: 'Vztahy',
    },
    articlesLabel: 'Články v češtině',
    allArticles: 'Všechny články',
    readMore: 'Číst dále',
    backToArticles: '← Zpět na články',
    publishedOn: 'Publikováno',
    categoryLabel: 'Kategorie',
    noArticles: 'V této kategorii zatím nejsou žádné články.',
  },
  vi: {
    label: 'Tiếng Việt',
    flag: '🇻🇳',
    categories: {
      'tai-chinh': 'Tài chính',
      'viec-lam': 'Việc làm',
      'suc-khoe': 'Sức khỏe',
      'nha-o': 'Nhà ở',
      'phap-luat': 'Pháp luật',
      'quan-he': 'Quan hệ',
    },
    articlesLabel: 'Bài viết tiếng Việt',
    allArticles: 'Tất cả bài viết',
    readMore: 'Đọc thêm',
    backToArticles: '← Quay lại bài viết',
    publishedOn: 'Đăng ngày',
    categoryLabel: 'Danh mục',
    noArticles: 'Chưa có bài viết nào trong danh mục này.',
  },
  is: {
    label: 'Íslenska',
    flag: '🇮🇸',
    categories: {
      fjarmal: 'Fjármál',
      vinna: 'Vinna',
      heilsa: 'Heilsa',
      husnaedi: 'Húsnæði',
      rettur: 'Réttur',
      samband: 'Samband',
    },
    articlesLabel: 'Greinar á íslensku',
    allArticles: 'Allar greinar',
    readMore: 'Lesa meira',
    backToArticles: '← Til baka í greinar',
    publishedOn: 'Birt þann',
    categoryLabel: 'Flokkur',
    noArticles: 'Engar greinar í þessum flokki ennþá.',
  },
};

// Boutique categories per language
export const boutiqueCategories = {
  en: {
    'health-wellness': 'Health & Wellness',
    'personal-development': 'Personal Development',
    'literature': 'Literature & Novels',
    'young-mothers': 'Young Mothers',
    'natural-medicine': 'Natural Medicine',
    'seniors': 'Seniors 60+',
    'digital-business': 'Digital Product Business & Global eCommerce',
    'finance': 'Personal Finance',
    'relationships': 'Relationships & Self-Love',
    'addiction': 'Addictions & Recovery',
    'travel': 'Travel',
  },
  fr: {
    'health-wellness': 'Santé & Bien-Être',
    'personal-development': 'Développement Personnel',
    'literature': 'Romans & Littérature',
    'young-mothers': 'Jeunes Mamans',
    'natural-medicine': 'Médecine Naturelle',
    'seniors': 'Pour nos Seniors',
    'digital-business': 'Business Digital & eCommerce',
    'finance': 'Finances Personnelles',
    'relationships': 'Relations & Amour de Soi',
    'addiction': 'Addictions & Dépendances',
    'travel': 'Voyage',
  },
  de: {
    'health-wellness': 'Gesundheit & Wohlbefinden',
    'personal-development': 'Persönliche Entwicklung',
    'literature': 'Romane & Literatur',
    'young-mothers': 'Junge Mütter',
    'natural-medicine': 'Naturmedizin',
    'seniors': 'Senioren 60+',
    'digital-business': 'Digitales Business & eCommerce',
    'finance': 'Persönliche Finanzen',
    'relationships': 'Beziehungen & Selbstliebe',
    'addiction': 'Sucht & Genesung',
    'travel': 'Reisen',
  },
  es: {
    'health-wellness': 'Salud & Bienestar',
    'personal-development': 'Desarrollo Personal',
    'literature': 'Novelas & Literatura',
    'young-mothers': 'Jóvenes Madres',
    'natural-medicine': 'Medicina Natural',
    'seniors': 'Seniors 60+',
    'digital-business': 'Negocio Digital & eCommerce',
    'finance': 'Finanzas Personales',
    'relationships': 'Relaciones & Amor Propio',
    'addiction': 'Adicciones & Recuperación',
    'travel': 'Viajes',
  },
  it: {
    'health-wellness': 'Salute & Benessere',
    'personal-development': 'Sviluppo Personale',
    'literature': 'Romanzi & Letteratura',
    'young-mothers': 'Giovani Mamme',
    'natural-medicine': 'Medicina Naturale',
    'seniors': 'Seniors 60+',
    'digital-business': 'Business Digitale & eCommerce',
    'finance': 'Finanza Personale',
    'relationships': 'Relazioni & Amor Proprio',
    'addiction': 'Dipendenze & Recupero',
    'travel': 'Viaggi',
  },
};

// Navigation labels (main site chrome)
export const navigation = {
  home: { fr: 'Accueil', en: 'Home', de: 'Startseite' },
  about: { fr: 'À propos', en: 'About', de: 'Über uns' },
  domains: { fr: 'Domaines', en: 'Domains', de: 'Bereiche' },
  resources: { fr: 'Ressources', en: 'Resources', de: 'Ressourcen' },
  articles: { fr: 'Articles', en: 'Articles', de: 'Artikel' },
  blogs: { fr: 'Blogs', en: 'Blogs', de: 'Blogs' },
};
